name: 'Synchronize staging branch'
description: 'Reset the staging branch with the main branch merging some branches identified by a specific label.'
inputs:
  repository:
    description: 'The repository name in Github owner/repository. e.g: TheMenu/monrepo'
    default: ${{ github.repository }}
  source-branch:
    description: 'The branch name used as base branch to synchronize the target one.'
    default: 'main'
  target-branch:
    description: 'The branch name used as target.'
    default: 'staging'
  label:
    description: 'The PR label that is used to find branch to merge in the target one.'
    default: 'in-staging'

branding:
  color: 'blue'
  icon: 'git-merge'

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
    - uses: actions4git/setup-git@v1
    - run: bun ${{ github.action_path }}/index.ts
      shell: bash
